name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Repository: textalk
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: "2.8.1" # you can use 1.12
          channel: "stable" # Currently you have to use beta channel for Flutter web.
      - name: Upgrades Flutter
        run: flutter upgrade
        working-directory: ./
      - name: Enable Web
        run: flutter config --enable-web
        working-directory: ./
      - name: Install Dependencies
        run: flutter packages get
        working-directory: ./
      - name: Build Web
        run: flutter build web --release
        working-directory: ./
      - name: Deploy
        run: |
          cd ./build/web
          sed -i 's#<base href="/">#<base href="/'$Repository'/">#g' index.html
          sed -i 's#<head>#<head>\n  <link rel="canonical" href="https://ychsue.github.io/'$Repository'/" />#i' index.html
          sed -i 's#"/"#"/'$Repository'/"#g' flutter_service_worker.js
          sed -i 's#"start_url": ".",#"start_url": "/'$Repository'/index.html",\n    "scope": "/'$Repository'/",#g' manifest.json
          git init
          git config user.name  "CI"
          git config user.email "flutter-ci@github.com"
          git remote add secure-origin https://${{ secrets.ACCESS_TOKEN2 }}@github.com/ychsue/$Repository.git
          git checkout -b gh-pages
          git add .
          git commit -m "Updated docs"
          git push --force secure-origin gh-pages